#!/usr/bin/env bash
# Print the CKAN sysadmin API key (CKAN 2.7 "token") for the ETL.
#
# The key lives in the CKAN database and is regenerated by prerun.py on every
# fresh boot, so it *inherently* resets with `docker compose down -v`. This
# script is the stability mechanism: after any (re)boot it prints the current
# working key, so ETL config can be captured with `./scripts/mint-token.sh`.
#
# Idempotent: safe to re-run; prints only the key on stdout.
set -euo pipefail
cd "$(dirname "$0")/.."

# The user named by CKAN_SYSADMIN_* (CKAN also auto-creates a "default" site
# user that is a sysadmin, so filter by name, not just the sysadmin flag).
admin_name=$(docker compose exec -T ckan printenv CKAN_SYSADMIN_NAME 2>/dev/null | tr -d '[:space:]')
if [ -z "$admin_name" ]; then
  echo "mint-token: CKAN_SYSADMIN_NAME not set — is the ckan service up?" >&2
  exit 1
fi
safe_name=${admin_name//\'/}  # internal value; drop quotes for the SQL literal

# Query the db container using its own POSTGRES_* env; SQL is passed via env so
# there is no shell-quoting conflict with the reserved word "user".
db_query() {
  docker compose exec -T -e MINT_SQL="$1" db \
    sh -c 'psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB" -tAc "$MINT_SQL"' \
    2>/dev/null
}

token=$(db_query "SELECT apikey FROM \"user\" WHERE name = '$safe_name' LIMIT 1;" \
  | tr -d '[:space:]')

# CKAN 2.7 normally auto-generates a key at user creation; mint one if absent.
if [ -z "$token" ]; then
  token=$(db_query "UPDATE \"user\" SET apikey = md5(random()::text || clock_timestamp()::text) WHERE name = '$safe_name' RETURNING apikey;" \
    | tr -d '[:space:]')
fi

if [ -z "$token" ]; then
  echo "mint-token: no apikey for user '$admin_name' — is the instance up and booted?" >&2
  exit 1
fi

printf '%s\n' "$token"
